# Request
string message
int16 initial_x
int16 initial_y
int16 initial_z
int16 final_x
int16 final_y
int16 final_z
---
# Result
string message
int16 x
int16 y
int16 z
---
# Feedback
string message
int16 current_x
int16 current_y
int16 current_z
